Repository xmtp/libxmtp, pull requests merged in 2024-04, with the labels that each got.

#643 Mutable Metadata group name Part 1
  Cargo.lock
  Cargo.toml
  bindings_ffi/Cargo.lock
  xmtp_mls/src/groups/group_mutable_metadata.rs
  xmtp_mls/src/groups/group_permissions.rs
  xmtp_mls/src/groups/intents.rs
  xmtp_mls/src/groups/sync.rs
  xmtp_mls/src/storage/encrypted_store/group_intent.rs
  xmtp_proto/src/gen/xmtp.identity.api.v1.rs
  xmtp_proto/src/gen/xmtp.message_api.v1.rs
  xmtp_proto/src/gen/xmtp.mls.api.v1.rs
  xmtp_proto/src/gen/xmtp.mls.database.rs
  xmtp_proto/src/gen/xmtp.mls.database.serde.rs
  xmtp_proto/src/gen/xmtp.mls.message_contents.rs
  xmtp_proto/src/gen/xmtp.mls.message_contents.serde.rs
Labels: Group Chat - Prod

#659 API error: setup error: transport error
  bindings_ffi/src/mls.rs
  xmtp_api_grpc/src/grpc_api_helper.rs
  xmtp_proto/src/api_client.rs
Labels: Partner Support

#666 Add AssociationState diff function
  xmtp_id/src/associations/state.rs
Labels: inbox-id

#667 Add XmtpIdentityClient trait to all implementations
  examples/cli/serializable.rs
  xmtp_mls/src/api_client_wrapper.rs
  xmtp_mls/src/builder.rs
  xmtp_mls/src/client.rs
  xmtp_mls/src/groups/members.rs
  xmtp_mls/src/groups/mod.rs
  xmtp_mls/src/groups/subscriptions.rs
  xmtp_mls/src/groups/sync.rs
  xmtp_mls/src/identity.rs
  xmtp_mls/src/subscriptions.rs
  xmtp_mls/src/types.rs
Labels: inbox-id

#668 Add ApiClientWrapper methods
  Cargo.lock
  Cargo.toml
  bindings_ffi/Cargo.lock
  xmtp_id/Cargo.toml
  xmtp_id/src/associations/association_log.rs
  xmtp_id/src/associations/mod.rs
  xmtp_id/src/associations/serialization.rs
  xmtp_id/src/associations/test_utils.rs
  xmtp_mls/Cargo.toml
  xmtp_mls/src/api/identity.rs
  xmtp_mls/src/api/mls.rs
  xmtp_mls/src/api/mod.rs
  xmtp_mls/src/api/test_utils.rs
  xmtp_mls/src/builder.rs
  xmtp_mls/src/client.rs
  xmtp_mls/src/groups/sync.rs
  xmtp_mls/src/identity.rs
  xmtp_mls/src/lib.rs
  xmtp_mls/src/subscriptions.rs
Labels: inbox-id

#669 Message send state
  bindings_ffi/src/mls.rs
  xmtp_mls/src/groups/mod.rs
  xmtp_mls/src/storage/encrypted_store/group_message.rs
Labels: Group Chat - Prod

#670 Add some Identity client methods
  xmtp_id/src/associations/association_log.rs
  xmtp_id/src/associations/mod.rs
  xmtp_id/src/associations/serialization.rs
  xmtp_mls/src/api/identity.rs
  xmtp_mls/src/api/mod.rs
  xmtp_mls/src/client.rs
  xmtp_mls/src/identity_updates.rs
  xmtp_mls/src/lib.rs
  xmtp_mls/src/storage/encrypted_store/identity_update.rs
  xmtp_mls/src/storage/mod.rs
Labels: inbox-id

#644 Mutable Metadata group name Part 2
  bindings_ffi/src/mls.rs
  xmtp_mls/src/configuration.rs
  xmtp_mls/src/groups/group_mutable_metadata.rs
  xmtp_mls/src/groups/intents.rs
  xmtp_mls/src/groups/mod.rs
  xmtp_mls/src/groups/sync.rs
  xmtp_mls/src/groups/validated_commit.rs
  xmtp_mls/src/identity.rs
Labels: Group Chat - Prod

#656 Get an Association State from a list of IdentityUpdates in Validation Service
  Cargo.lock
  Cargo.toml
  mls_validation_service/Cargo.toml
  mls_validation_service/src/handlers.rs
  xmtp_id/Cargo.toml
  xmtp_id/src/associations/association_log.rs
  xmtp_id/src/associations/hashes.rs
  xmtp_id/src/associations/mod.rs
  xmtp_id/src/associations/serialization.rs
  xmtp_id/src/associations/signature.rs
  xmtp_id/src/associations/state.rs
  xmtp_id/src/associations/test_utils.rs
  xmtp_proto/Cargo.toml
  xmtp_proto/src/gen/xmtp.identity.associations.rs
  xmtp_proto/src/gen/xmtp.identity.associations.serde.rs
  xmtp_proto/src/gen/xmtp.message_contents.rs
  xmtp_proto/src/gen/xmtp.message_contents.serde.rs
  xmtp_proto/src/gen/xmtp.mls_validation.v1.rs
  xmtp_proto/src/gen/xmtp.mls_validation.v1.serde.rs
  xmtp_proto/src/gen/xmtp.mls_validation.v1.tonic.rs
Labels: inbox-id

#677 Mutable Metadata group name Part 3
  Cargo.lock
  Cargo.toml
  bindings_ffi/Cargo.lock
  xmtp_mls/src/configuration.rs
  xmtp_mls/src/groups/group_mutable_metadata.rs
  xmtp_mls/src/groups/group_permissions.rs
  xmtp_mls/src/groups/intents.rs
  xmtp_mls/src/groups/mod.rs
  xmtp_mls/src/groups/sync.rs
  xmtp_mls/src/groups/validated_commit.rs
  xmtp_proto/src/gen/xmtp.identity.api.v1.rs
  xmtp_proto/src/gen/xmtp.message_api.v1.rs
  xmtp_proto/src/gen/xmtp.message_contents.rs
  xmtp_proto/src/gen/xmtp.message_contents.serde.rs
  xmtp_proto/src/gen/xmtp.mls.api.v1.rs
  xmtp_proto/src/gen/xmtp.mls.database.rs
  xmtp_proto/src/gen/xmtp.mls.database.serde.rs
  xmtp_proto/src/gen/xmtp.mls.message_contents.rs
  xmtp_proto/src/gen/xmtp.mls.message_contents.serde.rs
Labels: Group Chat - Prod

#673 signature verification
  Cargo.lock
  Cargo.toml
  bindings_ffi/Cargo.lock
  mls_validation_service/src/handlers.rs
  xmtp_cryptography/src/signature.rs
  xmtp_id/Cargo.toml
  xmtp_id/src/associations/association_log.rs
  xmtp_id/src/associations/builder.rs
  xmtp_id/src/associations/mod.rs
  xmtp_id/src/associations/serialization.rs
  xmtp_id/src/associations/signature.rs
  xmtp_id/src/associations/test_utils.rs
  xmtp_mls/src/builder.rs
  xmtp_mls/src/client.rs
  xmtp_mls/src/credential/grant_messaging_access_association.rs
  xmtp_mls/src/credential/legacy_create_identity_association.rs
  xmtp_mls/src/credential/mod.rs
  xmtp_mls/src/credential/validated_legacy_signed_public_key.rs
  xmtp_mls/src/groups/mod.rs
  xmtp_mls/src/identity/v3/mod.rs
  xmtp_mls/src/identity_updates.rs
  xmtp_mls/src/utils/address.rs
  xmtp_mls/src/utils/mod.rs
  xmtp_proto/src/gen/xmtp.identity.associations.rs
  xmtp_proto/src/gen/xmtp.identity.associations.serde.rs
Labels: inbox-id

#682 Adds AccountId
  Cargo.lock
  Cargo.toml
  bindings_ffi/Cargo.lock
  xmtp_api_grpc_gateway/Cargo.lock
  xmtp_cryptography/Cargo.toml
  xmtp_cryptography/src/signature.rs
  xmtp_id/Cargo.toml
  xmtp_id/src/associations/serialization.rs
  xmtp_id/src/associations/signature.rs
  xmtp_id/src/associations/test_utils.rs
  xmtp_proto/src/gen/xmtp.identity.associations.rs
  xmtp_proto/src/gen/xmtp.identity.associations.serde.rs
Labels: inbox-id

#684 Return a canMessage address bool hashmap
  bindings_ffi/src/mls.rs
  xmtp_mls/src/client.rs
Labels: Group Chat - Prod

#680 Allow message history sync
  xmtp_mls/src/builder.rs
  xmtp_mls/src/client.rs
  xmtp_mls/src/groups/message_history.rs
  xmtp_mls/src/storage/encrypted_store/group.rs
Labels: Group Chat - Prod

#686 Add high level identity actions
  Cargo.lock
  Cargo.toml
  bindings_ffi/Cargo.lock
  xmtp_id/Cargo.toml
  xmtp_id/src/associations/builder.rs
  xmtp_id/src/associations/mod.rs
  xmtp_id/src/associations/signature.rs
  xmtp_id/src/constants.rs
  xmtp_id/src/lib.rs
  xmtp_mls/Cargo.toml
  xmtp_mls/src/client.rs
  xmtp_mls/src/identity/mod.rs
  xmtp_mls/src/identity/v3/legacy.rs
  xmtp_mls/src/identity_updates.rs
  xmtp_proto/src/gen/xmtp.identity.api.v1.rs
  xmtp_proto/src/gen/xmtp.keystore_api.v1.rs
  xmtp_proto/src/gen/xmtp.keystore_api.v1.serde.rs
  xmtp_proto/src/gen/xmtp.message_api.v1.rs
  xmtp_proto/src/gen/xmtp.message_contents.rs
  xmtp_proto/src/gen/xmtp.message_contents.serde.rs
  xmtp_proto/src/gen/xmtp.mls.api.v1.rs
Labels: inbox-id

#672 Use `From` in xmtp_id serialization
  xmtp_id/src/associations/association_log.rs
  xmtp_id/src/associations/mod.rs
  xmtp_id/src/associations/serialization.rs
  xmtp_id/src/associations/signature.rs
  xmtp_mls/src/groups/message_history.rs
Labels: inbox-id

#690 Create installation diffs from updates
  xmtp_id/src/associations/state.rs
  xmtp_mls/src/groups/mod.rs
  xmtp_mls/src/identity_updates.rs
Labels: inbox-id

#691 Message History: Request and Reply structs
  xmtp_mls/src/builder.rs
  xmtp_mls/src/client.rs
  xmtp_mls/src/groups/message_history.rs
  xmtp_mls/src/storage/encrypted_store/group.rs
  xmtp_proto/Cargo.toml
  xmtp_proto/src/gen/mod.rs
  xmtp_proto/src/gen/xmtp.identity.rs
  xmtp_proto/src/gen/xmtp.identity.serde.rs
  xmtp_proto/src/gen/xmtp.mls.message_contents.rs
  xmtp_proto/src/gen/xmtp.mls.message_contents.serde.rs
Labels: Group Chat - Prod
